server:
  port: 8080

spring:
  application:
    name: votaciones
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD_DB}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect